kind: pipeline
type: docker
name: kubectl-test

steps:
  - name: deploy
    image: amazon/aws-cli:latest
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      AWS_REGION:
        from_secret: AWS_REGION
      EKS_CLUSTER_NAME:
        from_secret: EKS_CLUSTER_NAME
    commands:
      - curl -LO https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/kubectl
      - kubectl version --client
      - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
      - kubectl get nodes
      - kubectl get ns